version: "3"

services: #컨테이너를 정의하는 것=
  external_nginx:
    image: nginx:1.25.2 #사용되는 이미지
    container_name : external_nginx
    volumes:
      - /home/ubuntu/special_config/data/nginx:/etc/nginx/conf.d
      - /home/ubuntu/special_config/data/certbot/conf:/etc/letsencrypt #nginx
      - /home/ubuntu/special_config/data/certbot/www:/var/www/certbot
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot:latest
    container_name: special_certbot
    volumes:
      - /home/ubuntu/special_config/data/certbot/conf:/etc/letsencrypt #nginx
      - /home/ubuntu/special_config/data/certbot/www:/var/www/certbot
    restart: unless-stopped

